name: Close inactive issues
on:
  workflow_call:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 30
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: "bug, enhancement"
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been automatically marked as stale because it has
            not had recent activity. It will be closed if no further activity
            occurs. Thank you for your contributions.
          close-issue-message: >
            This issue was closed because it has been inactive for 30 days
            since being marked as stale.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

